#ifndef CONFIG_H
#define CONFIG_H

#define _WIN32_WINNT 0x0400

#define APP_NAME "Osteotomia"
#define ZOOM_IN_MAX 100
#define MAIN_WINDOW_W 640
#define MAIN_WINDOW_H 480
#define MAIN_WINDOW_MARGIN 0
#define FACTOR_16TO8 0.00390625
#define ZOOM_STEP 200
#define MOVE_STEP 50
#define POINT_RADIUS 10
#define PI 3.14159
#define WEDGE_SIZE_ANGLE 0.15
#define WEDGE_LOCATION_FACTOR 0.119
#define WEDGE_ANGLE 0.3
#define WARNING_LIMIT 0.2

#define SET_FILENAME "./settings.ini"
#define SET_CLAHE_TILE_GRID_SIZE 8
#define SET_CLAHE_CLIP_LIMIT 4
#define SET_GAUSSIAN_BLUR_KERNEL_SIZE 0
#define SET_CANNY_MIN_THRESHOLD 40
#define SET_CANNY_MAX_THRESHOLD 100
#define SET_HORINZONTAL_REMOVE 3
#define SET_VERTICAL_REMOVE 3
#define SET_AUTO_MIN_ANGLE -0.5
#define SET_AUTO_MAX_ANGLE 0.5
#define SET_AUTO_ANG_STEP 64
#define SET_AUTO_MIN_LINEAR 40
#define SET_AUTO_MAX_LINEAR 100
#define SET_AUTO_LINEAR_STEP 1
#define SET_AUTO_LINEAR_SIZE 1
#define SET_AUTO_SCALE 8

#endif // CONFIG_H
